### ISSUE TITLE
Follow one .then() syntax

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/node-api-promises#10]
The example code uses several different .then syntaxes. Use one. Stick to it.

**Comment by gaand** [comment]
I'm not sure what this means.  Is this a formatting issue?

**Comment by payne-chris-r** [comment]
Yes. Formatting. All should look like this:
```js
doAsyncSomething()
  .then()
  .then()
  .catch()
```

NOT
```js
doAsyncSomething().then()
```
OR
```js
doAsyncSomething()
.then()
.catch()
```

**Comment by gaand** [comment]
Agreed.  @ga-wdi-boston/core without objection?

**Comment by raq929** [comment]
Agreed.

**Comment by raq929** [comment]
Per @jrhorn424 we need to make this consistent across other repos.

**Comment by jrhorn424** [comment]
(props to @raq929 for catching that we were parsing @payne-chris-r's comment differently)

As it currently reads to me, in English, to me:

> Formatting for Promise chains should be either flush or indented two spaces, **not** all on one line.

As it currently reads to @raq929, with correct English (😉):

> Formatting for Promise chains should **not** be all on one line **nor** flush, but instead indented with two spaces.

Turns out, "nor" versus "or" is a thing.

Fun party game: try to guess whether it was a traumatic English class, or a traumatic formal logic class, which forced me to learn the difference. (<-- good job, me, on parallel construction and favoring "which" over "that")
